version: '3.8'

services:
  api_booth_pm:
    build: .
    command: sh -c "yarn install && yarn dev"
    ports:
      - "8001:8001"
    volumes:
      - .:/usr/src/poster_app
      - /usr/src/poster_app/node_modules